### ISSUE TITLE
Server showing node as unusable 

### ISSUE THREAD

**Issue by vidit-bhatia** [Azure/BatchAI#19] opened 2018-01-16 23:41 UTC
My server is showing the nodes as unusable . The server use to work just few days back . I tried going on to the node as described in https://github.com/Azure/BatchAI/issues/9 .

![image](https://user-images.githubusercontent.com/3845645/35018335-d62e8368-fad5-11e7-9154-8671b0e51dce.png)

There was nothing mentioned other than that there is an internal error. Is there any way I can start my server or fix these nodes.
{"Code":"InternalError","Message":"","Category":"InternalError","ExitCode":1,"Details":null}

**Comment by AlexanderYukhanov** [comment] 2018-01-18 00:07
Thanks for reporting the problem. can you please provide stdout.txt and stderr.txt from /mnt/batch/tasks/startup/ for investigation? You can solve the problem by resizing the cluster to 0 and back to 2.
az batchai cluster resize -n <clustername> -g <resource group> -t 0
az batchai cluster resize -n <clustername> -g <resource group> -t 1

Thanks,
Alex

**Comment by AlexanderYukhanov** [comment] 2018-01-19 19:33
vidit-bhatia, I see you still have one node in unusable state. You probably would like to delete it if you are not using it via ssh, because it's still allocated and is considered to be used by you (so, it will be included in the bill).  You can just set min size for your cluster to 0 to delete nodes when you are not using them.

**Comment by vidit-bhatia** [comment] 2018-01-19 22:54
@AlexanderYukhanov I set the minimum number of nodes to 0 but now when I post a new job the nodes do not auto scale and create new nodes according to the job requirements

**Comment by AlexanderYukhanov** [comment] 2018-01-19 23:22
Please note, system checks if it needs to resize cluster every 5 mins. So, it can take up to 5 mins for BatchAI to start nodes allocation after you submit a job.

**Comment by AlexanderYukhanov** [comment] 2018-01-19 23:37
vidit-bhatia. Can you please recreate your cluster? The issue is that your cluster was created before the recent ubuntu meltdown patch and kernel update. Now when your cluster is trying to allocate nodes it gets new kernel but old drivers.

**Comment by vidit-bhatia** [comment] 2018-01-19 23:50
@AlekseiPolkovnikov  I will look into it on Monday see how that can be done as the cluster is used already by some people.

**Comment by AlexanderYukhanov** [comment] 2018-01-20 01:44
We have implemented a workaround on our side to make nodes after resize to pick up new drivers. So, you may keep the cluster and just make sure that all your unusable nodes removed

**Comment by vidit-bhatia** [comment] 2018-01-22 17:57
Looking into it

**Closed** 2018-01-23 18:49 UTC
